library(ggplot2)
library(dplyr)

# ============================================================
# NOTA METODOLOGICA (para Methods del paper):
# Se excluyen los primeros y ultimos 10 Mb de cada cromosoma
# (masking de regiones telomericas y pericentromericas).
# Razon: estas regiones contienen secuencias repetitivas de
# baja complejidad (satelites, secuencias subtelomericas) que
# generan falsas senales de homocigosidad en el HMM de ROHan
# por mapeo inespecifico de lecturas cortas de aDNA. La senal
# de p(ROH) elevada en los primeros 0-9 Mb de cromosomas
# grandes (chr1, chr2, chr5) es un artefacto sistematico
# confirmado por su presencia uniforme en todos los especimenes
# independientemente de su nivel de heterocigosidad.
# Referencia: Mafessoni et al. 2020 (ROHan paper) recomienda
# aplicar mascara de mappabilidad para analisis de aDNA.
# ============================================================

TELOMERE_MASK_MB <- 10  # excluir primeros y ultimos 10 Mb

specimens <- c("femurXIII", "femur_fragment", "molar_L35", "scapula")
labels_sp <- c("FemurXIII", "Femur fragment", "Molar L35", "Scapula")
autosomes <- paste0("chr", 1:22)

# Longitudes aproximadas cromosomas hg38 (Mb)
chr_lengths <- c(249, 242, 198, 190, 181, 171, 159, 145, 138, 133,
                 135, 133, 114, 107, 102,  90,  83,  80,  59,  64,
                  47,  51)
names(chr_lengths) <- autosomes

all_data <- data.frame()
for (i in seq_along(specimens)) {
  sp <- specimens[i]
  df <- read.table(
    gzfile(paste0("~/PopSize/results/roh/", sp, ".mid.hmmp.gz")),
    header = TRUE, sep = "\t", comment.char = "#",
    col.names = c("chrom", "begin", "end", "p_roh", "p_nonroh"),
    na.strings = "NA"
  )
  # Filtrar solo autosomas
  df <- df[df$chrom %in% autosomes, ]

  # Aplicar mascara telomerica/pericentromerica
  df <- df %>%
    mutate(
      chr_len_mb = chr_lengths[chrom],
      begin_mb   = begin / 1e6,
      end_mb     = end   / 1e6
    ) %>%
    filter(
      begin_mb >= TELOMERE_MASK_MB,
      end_mb   <= (chr_len_mb - TELOMERE_MASK_MB)
    )

  # NA -> 0 (sin cobertura)
  df$p_roh[is.na(df$p_roh)] <- 0

  df$specimen <- labels_sp[i]
  df$mid_mb   <- (df$begin + df$end) / 2e6

  all_data <- rbind(all_data, df)
}

all_data$specimen <- factor(all_data$specimen, levels = rev(labels_sp))
all_data$chrom    <- factor(all_data$chrom,
                             levels  = autosomes,
                             labels  = paste0("Chr ", 1:22))

p <- ggplot(all_data, aes(x = mid_mb, y = specimen, fill = p_roh)) +
  geom_tile(width = 3, height = 0.85) +
  facet_wrap(~ chrom, nrow = 4, scales = "free_x") +
  scale_fill_gradientn(
    colors = c("white", "#E6F1FB", "#85B7EB", "#185FA5", "#042C53"),
    values = c(0, 0.05, 0.20, 0.50, 1),
    limits = c(0, 1),
    name   = "p(ROH)",
    breaks = c(0, 0.25, 0.5, 0.75, 1),
    labels = c("0", "0.25", "0.50", "0.75", "1.0"),
    na.value = "white"
  ) +
  labs(
    title    = "ROH probability across autosomes - Sima de los Huesos (~430 ka)",
    subtitle = paste0(
      "ROHan HMM posterior p(ROH) per 3 Mb window (mid estimate)  .  hg38  .  transversions only\n",
      "Telomeric/pericentromeric regions masked (first and last ", TELOMERE_MASK_MB, " Mb per chromosome)"
    ),
    x = "Position (Mb)",
    y = NULL
  ) +
  theme_minimal(base_size = 9) +
  theme(
    plot.background  = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    strip.background = element_rect(fill = "grey92", color = NA),
    strip.text  = element_text(size = 8, face = "bold", color = "black"),
    axis.text.x = element_text(size = 6, color = "grey40"),
    axis.text.y = element_text(size = 8, color = "black"),
    legend.position  = "right",
    legend.title     = element_text(size = 9),
    panel.grid       = element_blank(),
    plot.title       = element_text(size = 11, face = "bold", color = "black"),
    plot.subtitle    = element_text(size =  8, color = "grey40"),
    panel.spacing    = unit(0.4, "lines")
  )

ggsave("~/PopSize/results/ideogram_ROH_SH_v3.pdf",
       p, width = 16, height = 10, device = "pdf", bg = "white")
ggsave("~/PopSize/results/ideogram_ROH_SH_v3.png",
       p, width = 16, height = 10, dpi = 300, bg = "white")

cat("✓ Ideograma v3 (masked) guardado\n")

# Estadisticas por especimen (post-mascaras)
cat("\n=== p(ROH) media por especimen (masked) ===\n")
all_data %>%
  group_by(specimen) %>%
  summarise(
    mean_pROH  = round(mean(p_roh, na.rm = TRUE), 4),
    max_pROH   = round(max(p_roh,  na.rm = TRUE), 4),
    n_windows  = n(),
    pct_high   = round(mean(p_roh > 0.25, na.rm = TRUE) * 100, 1)
  ) %>%
  arrange(desc(mean_pROH)) %>%
  print()

cat("\n=== Nota metodologica para Methods ===\n")
cat(paste0(
  "Telomeric and pericentromeric regions (first and last ", TELOMERE_MASK_MB,
  " Mb per autosome) were excluded from ROH probability visualization ",
  "due to systematic false-positive ROH signals generated by repetitive ",
  "low-complexity sequences (satellite DNA, subtelomeric repeats) causing ",
  "non-specific mapping of short ancient DNA reads. This artefact was ",
  "identified as a uniform high-p(ROH) signal in all specimens ",
  "irrespective of their heterozygosity levels, consistent with a ",
  "technical rather than biological origin. Mappability masking is ",
  "recommended for ancient DNA ROH analyses (Mafessoni et al. 2020).\n"
))
